server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

        - id: job-service
          uri: lb://JOB-SERVICE
          predicates:
            - Path=/api/jobs/**

        - id: resume-service
          uri: lb://RESUME-SERVICE
          predicates:
            - Path=/api/resumes/**

        - id: job-service
          uri: lb://JOB-SERVICE
          predicates:
            - Path=/api/jobs/**

        - id: applicationTracking-service
          uri: lb://APPLICATIONTRACKING-SERVICE
          predicates:
            - Path=/api/applications/**

        - id: skill-service
          uri: lb://SKILL-SERVICE
          predicates:
            - Path=/api/skills/**

        - id: user-skill-service
          uri: lb://SKILL-SERVICE
          predicates:
            - Path=/api/user-skills/**

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/